#!/bin/sh 

# Small bash script to quickly fork a project in github
# Version 0.1
# Todo: 
#   * filters if upstream repo does not exist of if already forked...
#   * https protocol
#   * ...
# 
# Need hub. To install, type brew install hub


print_help() {
    cat <<EOF
Usage: $0 git@github.com:<user>/<repo.git> 

  Fork and create and upstream 
  This assumes you have hub installed
    (brew install hub)
EOF
}
                       
if [[ ! $# -eq 1 ]] ; then  
  print_help           
  exit 1               
fi

# Make sure we have hub
if ! which hub >/dev/null ; then
  echo "You need to install hub\n $ brew install hub"
  exit 1               
fi

# Removes all branches that are both on upstream and origin
remove_all_branches() {
  # remove other people's branches from your github repo
  # keep just the master
  for i in `git branch -r | grep upstream | grep -v -E "upstream/master" |  sed -e "s/\ \ upstream\///"`; do git push origin :${i}; done
}

LOCAL_USER=`echo $@ | cut -d : -f 2 | cut -d / -f 1`
LOCAL_REPO=`echo $@ | cut -d : -f 2 | cut -d / -f 2 | sed 's/.git//'`
HUB_USER=`grep -A 3 github.com ~/.config/hub | grep user: | sed 's/  user: //'`

if [ -d ${LOCAL_REPO} ]; then
  echo "The directory ${LOCAL_REPO} already exists"
  exit 1
fi

echo "\nCloning ${@} from user ${LOCAL_USER} and repo ${LOCAL_REPO} into github user ${HUB_USER}\n"
git clone -o upstream $@ 
cd $LOCAL_REPO
hub fork
git remote rename ${HUB_USER} origin
git remote update
git remote prune origin
git remote prune upstream

remove_all_branches
