#!/usr/bin/env ruby
# encoding: utf-8

require 'optparse'
begin
  require 'pry'
rescue LoadError
  puts "Pry is not availble"
end


file = File.symlink?(__FILE__) ? File.realpath(__FILE__) : __FILE__
Dir["#{File.expand_path("../lib", file)}/**/*.rb"].map{|x| require x}

# TODO:
# Exisitng directory
# GHE

options = {}

option_parser = OptionParser.new do |opts|
  banner = ["Usage: #{File.basename($PROGRAM_NAME)} [options] git@github.com:<user>/<repo.git>\n"]
  banner << "Fork and create and upstream"
  banner << "This assumes you have hub installed"
  banner << "(brew install hub)"
  opts.banner = banner.join("\n")
  # Create a switch
  opts.on("--[no-]pullrequest", "Download pull requests") do |pullrequest|
      options[:download_pull_request] = pullrequest
  end
  # Create a flag
  opts.on("-u", "--user USER", "Github user to use") do |user|
    options[:user] = user
  end
end

option_parser.parse!

if ARGV.empty?
  puts "Error, you must supply a project to fork"
  puts
  puts option_parser.help
  exit 1
else
  options[:repository] = Forking::Repository.new(ARGV.shift)
  options[:directory] = ARGV.shift
end

a = Forking::Handler.new(options)
a.handle
